namespace YTPDeluxe
{
    partial class Main
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.MenuStrip menuStrip;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabLibraries;
        private System.Windows.Forms.TabPage tabEffects;
        private System.Windows.Forms.TabPage tabRender;
        private System.Windows.Forms.ListBox lstLibraries;
        private System.Windows.Forms.Button btnImportMaterials;
        private System.Windows.Forms.Button btnImportTransitions;
        private System.Windows.Forms.Button btnImportIntros;
        private System.Windows.Forms.Button btnImportOutros;
        private System.Windows.Forms.Button btnImportOverlays;
        private System.Windows.Forms.Button btnImportSoundFx;
        private System.Windows.Forms.Button btnImportMusic;
        private System.Windows.Forms.Button btnImportRave;
        private System.Windows.Forms.Button btnImportVocoder;
        private System.Windows.Forms.CheckedListBox clbEffects;
        private System.Windows.Forms.TrackBar trkProbability;
        private System.Windows.Forms.TrackBar trkIntensity;
        private System.Windows.Forms.TrackBar trkStackLevel;
        private System.Windows.Forms.Label lblProbability;
        private System.Windows.Forms.Label lblIntensity;
        private System.Windows.Forms.Label lblStackLevel;
        private System.Windows.Forms.Button btnSelectAllEffects;
        private System.Windows.Forms.Button btnClearEffects;
        private System.Windows.Forms.Button btnResetDefaults;
        private System.Windows.Forms.Button btnSavePreset;
        private System.Windows.Forms.Button btnLoadPreset;
        private System.Windows.Forms.TextBox txtFfmpegPath;
        private System.Windows.Forms.TextBox txtOutputPath;
        private System.Windows.Forms.Button btnBrowseFfmpeg;
        private System.Windows.Forms.Button btnBrowseOutput;
        private System.Windows.Forms.NumericUpDown nudClipCount;
        private System.Windows.Forms.NumericUpDown nudMinSeconds;
        private System.Windows.Forms.NumericUpDown nudMaxSeconds;
        private System.Windows.Forms.CheckBox chkChaosTimeline;
        private System.Windows.Forms.CheckBox chkAutoSourceSwitcher;
        private System.Windows.Forms.CheckBox chkCleanupTemp;
        private System.Windows.Forms.Button btnStartRender;
        private System.Windows.Forms.ProgressBar progressBar;
        private System.Windows.Forms.Label lblRenderStatus;
        private System.Windows.Forms.TextBox txtLog;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.menuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabControl = new System.Windows.Forms.TabControl();
            this.tabLibraries = new System.Windows.Forms.TabPage();
            this.tabEffects = new System.Windows.Forms.TabPage();
            this.tabRender = new System.Windows.Forms.TabPage();
            this.lstLibraries = new System.Windows.Forms.ListBox();
            this.btnImportMaterials = new System.Windows.Forms.Button();
            this.btnImportTransitions = new System.Windows.Forms.Button();
            this.btnImportIntros = new System.Windows.Forms.Button();
            this.btnImportOutros = new System.Windows.Forms.Button();
            this.btnImportOverlays = new System.Windows.Forms.Button();
            this.btnImportSoundFx = new System.Windows.Forms.Button();
            this.btnImportMusic = new System.Windows.Forms.Button();
            this.btnImportRave = new System.Windows.Forms.Button();
            this.btnImportVocoder = new System.Windows.Forms.Button();
            this.clbEffects = new System.Windows.Forms.CheckedListBox();
            this.trkProbability = new System.Windows.Forms.TrackBar();
            this.trkIntensity = new System.Windows.Forms.TrackBar();
            this.trkStackLevel = new System.Windows.Forms.TrackBar();
            this.lblProbability = new System.Windows.Forms.Label();
            this.lblIntensity = new System.Windows.Forms.Label();
            this.lblStackLevel = new System.Windows.Forms.Label();
            this.btnSelectAllEffects = new System.Windows.Forms.Button();
            this.btnClearEffects = new System.Windows.Forms.Button();
            this.btnResetDefaults = new System.Windows.Forms.Button();
            this.btnSavePreset = new System.Windows.Forms.Button();
            this.btnLoadPreset = new System.Windows.Forms.Button();
            this.txtFfmpegPath = new System.Windows.Forms.TextBox();
            this.txtOutputPath = new System.Windows.Forms.TextBox();
            this.btnBrowseFfmpeg = new System.Windows.Forms.Button();
            this.btnBrowseOutput = new System.Windows.Forms.Button();
            this.nudClipCount = new System.Windows.Forms.NumericUpDown();
            this.nudMinSeconds = new System.Windows.Forms.NumericUpDown();
            this.nudMaxSeconds = new System.Windows.Forms.NumericUpDown();
            this.chkChaosTimeline = new System.Windows.Forms.CheckBox();
            this.chkAutoSourceSwitcher = new System.Windows.Forms.CheckBox();
            this.chkCleanupTemp = new System.Windows.Forms.CheckBox();
            this.btnStartRender = new System.Windows.Forms.Button();
            this.progressBar = new System.Windows.Forms.ProgressBar();
            this.lblRenderStatus = new System.Windows.Forms.Label();
            this.txtLog = new System.Windows.Forms.TextBox();
            this.menuStrip.SuspendLayout();
            this.tabControl.SuspendLayout();
            this.tabLibraries.SuspendLayout();
            this.tabEffects.SuspendLayout();
            this.tabRender.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkProbability)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.trkIntensity)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.trkStackLevel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudClipCount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMinSeconds)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxSeconds)).BeginInit();
            this.SuspendLayout();
            this.menuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { this.fileToolStripMenuItem, this.helpToolStripMenuItem });
            this.menuStrip.Location = new System.Drawing.Point(0, 0);
            this.menuStrip.Name = "menuStrip";
            this.menuStrip.Size = new System.Drawing.Size(984, 24);
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { this.exitToolStripMenuItem });
            this.fileToolStripMenuItem.Text = "&File";
            this.exitToolStripMenuItem.Text = "E&xit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.exitToolStripMenuItem_Click);
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { this.aboutToolStripMenuItem });
            this.helpToolStripMenuItem.Text = "&Help";
            this.aboutToolStripMenuItem.Text = "&About";
            this.aboutToolStripMenuItem.Click += new System.EventHandler(this.aboutToolStripMenuItem_Click);
            this.tabControl.Controls.Add(this.tabLibraries);
            this.tabControl.Controls.Add(this.tabEffects);
            this.tabControl.Controls.Add(this.tabRender);
            this.tabControl.Location = new System.Drawing.Point(12, 36);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new System.Drawing.Size(960, 388);
            this.tabLibraries.Controls.Add(this.lstLibraries);
            this.tabLibraries.Controls.Add(this.btnImportMaterials);
            this.tabLibraries.Controls.Add(this.btnImportTransitions);
            this.tabLibraries.Controls.Add(this.btnImportIntros);
            this.tabLibraries.Controls.Add(this.btnImportOutros);
            this.tabLibraries.Controls.Add(this.btnImportOverlays);
            this.tabLibraries.Controls.Add(this.btnImportSoundFx);
            this.tabLibraries.Controls.Add(this.btnImportMusic);
            this.tabLibraries.Controls.Add(this.btnImportRave);
            this.tabLibraries.Controls.Add(this.btnImportVocoder);
            this.tabLibraries.Text = "Media Libraries";
            this.lstLibraries.Location = new System.Drawing.Point(18, 18);
            this.lstLibraries.Size = new System.Drawing.Size(300, 303);
            this.btnImportMaterials.Location = new System.Drawing.Point(344, 18);
            this.btnImportMaterials.Size = new System.Drawing.Size(160, 30);
            this.btnImportMaterials.Text = "Import Materials";
            this.btnImportMaterials.Click += new System.EventHandler(this.btnImportMaterials_Click);
            this.btnImportTransitions.Location = new System.Drawing.Point(344, 58);
            this.btnImportTransitions.Size = new System.Drawing.Size(160, 30);
            this.btnImportTransitions.Text = "Import Transitions";
            this.btnImportTransitions.Click += new System.EventHandler(this.btnImportTransitions_Click);
            this.btnImportIntros.Location = new System.Drawing.Point(344, 98);
            this.btnImportIntros.Size = new System.Drawing.Size(160, 30);
            this.btnImportIntros.Text = "Import Intros";
            this.btnImportIntros.Click += new System.EventHandler(this.btnImportIntros_Click);
            this.btnImportOutros.Location = new System.Drawing.Point(344, 138);
            this.btnImportOutros.Size = new System.Drawing.Size(160, 30);
            this.btnImportOutros.Text = "Import Outros";
            this.btnImportOutros.Click += new System.EventHandler(this.btnImportOutros_Click);
            this.btnImportOverlays.Location = new System.Drawing.Point(344, 178);
            this.btnImportOverlays.Size = new System.Drawing.Size(160, 30);
            this.btnImportOverlays.Text = "Import Overlays";
            this.btnImportOverlays.Click += new System.EventHandler(this.btnImportOverlays_Click);
            this.btnImportSoundFx.Location = new System.Drawing.Point(532, 18);
            this.btnImportSoundFx.Size = new System.Drawing.Size(160, 30);
            this.btnImportSoundFx.Text = "Import Sound FX";
            this.btnImportSoundFx.Click += new System.EventHandler(this.btnImportSoundFx_Click);
            this.btnImportMusic.Location = new System.Drawing.Point(532, 58);
            this.btnImportMusic.Size = new System.Drawing.Size(160, 30);
            this.btnImportMusic.Text = "Import Music";
            this.btnImportMusic.Click += new System.EventHandler(this.btnImportMusic_Click);
            this.btnImportRave.Location = new System.Drawing.Point(532, 98);
            this.btnImportRave.Size = new System.Drawing.Size(160, 30);
            this.btnImportRave.Text = "Import Rave";
            this.btnImportRave.Click += new System.EventHandler(this.btnImportRave_Click);
            this.btnImportVocoder.Location = new System.Drawing.Point(532, 138);
            this.btnImportVocoder.Size = new System.Drawing.Size(160, 30);
            this.btnImportVocoder.Text = "Import Vocoder";
            this.btnImportVocoder.Click += new System.EventHandler(this.btnImportVocoder_Click);
            this.tabEffects.Controls.Add(this.clbEffects);
            this.tabEffects.Controls.Add(this.trkProbability);
            this.tabEffects.Controls.Add(this.trkIntensity);
            this.tabEffects.Controls.Add(this.trkStackLevel);
            this.tabEffects.Controls.Add(this.lblProbability);
            this.tabEffects.Controls.Add(this.lblIntensity);
            this.tabEffects.Controls.Add(this.lblStackLevel);
            this.tabEffects.Controls.Add(this.btnSelectAllEffects);
            this.tabEffects.Controls.Add(this.btnClearEffects);
            this.tabEffects.Controls.Add(this.btnResetDefaults);
            this.tabEffects.Controls.Add(this.btnSavePreset);
            this.tabEffects.Controls.Add(this.btnLoadPreset);
            this.tabEffects.Text = "Effects Panel";
            this.clbEffects.CheckOnClick = true;
            this.clbEffects.Location = new System.Drawing.Point(18, 18);
            this.clbEffects.Size = new System.Drawing.Size(340, 319);
            this.clbEffects.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.clbEffects_ItemCheck);
            this.clbEffects.SelectedIndexChanged += new System.EventHandler(this.clbEffects_SelectedIndexChanged);
            this.trkProbability.Location = new System.Drawing.Point(390, 42);
            this.trkProbability.Maximum = 100;
            this.trkProbability.Size = new System.Drawing.Size(300, 45);
            this.trkProbability.Scroll += new System.EventHandler(this.trkProbability_Scroll);
            this.trkIntensity.Location = new System.Drawing.Point(390, 112);
            this.trkIntensity.Maximum = 100;
            this.trkIntensity.Size = new System.Drawing.Size(300, 45);
            this.trkIntensity.Scroll += new System.EventHandler(this.trkIntensity_Scroll);
            this.trkStackLevel.Location = new System.Drawing.Point(390, 182);
            this.trkStackLevel.Minimum = 1;
            this.trkStackLevel.Maximum = 8;
            this.trkStackLevel.Size = new System.Drawing.Size(300, 45);
            this.trkStackLevel.Scroll += new System.EventHandler(this.trkStackLevel_Scroll);
            this.lblProbability.Location = new System.Drawing.Point(704, 50);
            this.lblProbability.Size = new System.Drawing.Size(180, 20);
            this.lblProbability.Text = "Probability";
            this.lblIntensity.Location = new System.Drawing.Point(704, 120);
            this.lblIntensity.Size = new System.Drawing.Size(180, 20);
            this.lblIntensity.Text = "Intensity";
            this.lblStackLevel.Location = new System.Drawing.Point(704, 190);
            this.lblStackLevel.Size = new System.Drawing.Size(180, 20);
            this.lblStackLevel.Text = "Stack";
            this.btnSelectAllEffects.Location = new System.Drawing.Point(390, 252);
            this.btnSelectAllEffects.Size = new System.Drawing.Size(130, 30);
            this.btnSelectAllEffects.Text = "Select All Effects";
            this.btnSelectAllEffects.Click += new System.EventHandler(this.btnSelectAllEffects_Click);
            this.btnClearEffects.Location = new System.Drawing.Point(532, 252);
            this.btnClearEffects.Size = new System.Drawing.Size(130, 30);
            this.btnClearEffects.Text = "Clear Selection";
            this.btnClearEffects.Click += new System.EventHandler(this.btnClearEffects_Click);
            this.btnResetDefaults.Location = new System.Drawing.Point(674, 252);
            this.btnResetDefaults.Size = new System.Drawing.Size(130, 30);
            this.btnResetDefaults.Text = "Reset to Default";
            this.btnResetDefaults.Click += new System.EventHandler(this.btnResetDefaults_Click);
            this.btnSavePreset.Location = new System.Drawing.Point(390, 300);
            this.btnSavePreset.Size = new System.Drawing.Size(130, 30);
            this.btnSavePreset.Text = "Save Preset";
            this.btnSavePreset.Click += new System.EventHandler(this.btnSavePreset_Click);
            this.btnLoadPreset.Location = new System.Drawing.Point(532, 300);
            this.btnLoadPreset.Size = new System.Drawing.Size(130, 30);
            this.btnLoadPreset.Text = "Load Preset";
            this.btnLoadPreset.Click += new System.EventHandler(this.btnLoadPreset_Click);
            this.tabRender.Controls.Add(this.txtFfmpegPath);
            this.tabRender.Controls.Add(this.txtOutputPath);
            this.tabRender.Controls.Add(this.btnBrowseFfmpeg);
            this.tabRender.Controls.Add(this.btnBrowseOutput);
            this.tabRender.Controls.Add(this.nudClipCount);
            this.tabRender.Controls.Add(this.nudMinSeconds);
            this.tabRender.Controls.Add(this.nudMaxSeconds);
            this.tabRender.Controls.Add(this.chkChaosTimeline);
            this.tabRender.Controls.Add(this.chkAutoSourceSwitcher);
            this.tabRender.Controls.Add(this.chkCleanupTemp);
            this.tabRender.Controls.Add(this.btnStartRender);
            this.tabRender.Controls.Add(this.progressBar);
            this.tabRender.Controls.Add(this.lblRenderStatus);
            this.tabRender.Text = "Render Settings";
            this.txtFfmpegPath.Location = new System.Drawing.Point(18, 24);
            this.txtFfmpegPath.Size = new System.Drawing.Size(650, 20);
            this.btnBrowseFfmpeg.Location = new System.Drawing.Point(684, 22);
            this.btnBrowseFfmpeg.Size = new System.Drawing.Size(120, 24);
            this.btnBrowseFfmpeg.Text = "FFmpeg Path";
            this.btnBrowseFfmpeg.Click += new System.EventHandler(this.btnBrowseFfmpeg_Click);
            this.txtOutputPath.Location = new System.Drawing.Point(18, 64);
            this.txtOutputPath.Size = new System.Drawing.Size(650, 20);
            this.btnBrowseOutput.Location = new System.Drawing.Point(684, 62);
            this.btnBrowseOutput.Size = new System.Drawing.Size(120, 24);
            this.btnBrowseOutput.Text = "Output MP4";
            this.btnBrowseOutput.Click += new System.EventHandler(this.btnBrowseOutput_Click);
            this.nudClipCount.Location = new System.Drawing.Point(18, 112);
            this.nudClipCount.Minimum = 1;
            this.nudClipCount.Maximum = 200;
            this.nudClipCount.Value = 12;
            this.nudMinSeconds.Location = new System.Drawing.Point(150, 112);
            this.nudMinSeconds.Minimum = 1;
            this.nudMinSeconds.Maximum = 60;
            this.nudMinSeconds.Value = 1;
            this.nudMaxSeconds.Location = new System.Drawing.Point(282, 112);
            this.nudMaxSeconds.Minimum = 1;
            this.nudMaxSeconds.Maximum = 120;
            this.nudMaxSeconds.Value = 5;
            this.chkChaosTimeline.Location = new System.Drawing.Point(18, 156);
            this.chkChaosTimeline.Size = new System.Drawing.Size(180, 24);
            this.chkChaosTimeline.Text = "Chaos Timeline mode";
            this.chkAutoSourceSwitcher.Location = new System.Drawing.Point(18, 186);
            this.chkAutoSourceSwitcher.Size = new System.Drawing.Size(180, 24);
            this.chkAutoSourceSwitcher.Text = "Auto Source Switcher";
            this.chkCleanupTemp.Location = new System.Drawing.Point(18, 216);
            this.chkCleanupTemp.Size = new System.Drawing.Size(180, 24);
            this.chkCleanupTemp.Text = "Cleanup temp files";
            this.btnStartRender.Location = new System.Drawing.Point(18, 270);
            this.btnStartRender.Size = new System.Drawing.Size(160, 40);
            this.btnStartRender.Text = "Start Render";
            this.btnStartRender.Click += new System.EventHandler(this.btnStartRender_Click);
            this.progressBar.Location = new System.Drawing.Point(200, 278);
            this.progressBar.Size = new System.Drawing.Size(520, 24);
            this.lblRenderStatus.Location = new System.Drawing.Point(736, 282);
            this.lblRenderStatus.Size = new System.Drawing.Size(180, 20);
            this.lblRenderStatus.Text = "Idle";
            this.txtLog.Location = new System.Drawing.Point(12, 436);
            this.txtLog.Multiline = true;
            this.txtLog.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtLog.Size = new System.Drawing.Size(960, 164);
            this.txtLog.ReadOnly = true;
            this.ClientSize = new System.Drawing.Size(984, 612);
            this.Controls.Add(this.txtLog);
            this.Controls.Add(this.tabControl);
            this.Controls.Add(this.menuStrip);
            this.MainMenuStrip = this.menuStrip;
            this.Name = "Main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "YTP++ Deluxe";
            this.menuStrip.ResumeLayout(false);
            this.menuStrip.PerformLayout();
            this.tabControl.ResumeLayout(false);
            this.tabLibraries.ResumeLayout(false);
            this.tabEffects.ResumeLayout(false);
            this.tabEffects.PerformLayout();
            this.tabRender.ResumeLayout(false);
            this.tabRender.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.trkProbability)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.trkIntensity)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.trkStackLevel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudClipCount)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMinSeconds)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxSeconds)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
